apiVersion: batch/v1
kind: Job
metadata:
  name: aed-clustering
spec:
  template:
    spec:
      containers:
      - name: aed-clustering-container
        image: 887044485231.dkr.ecr.eu-west-1.amazonaws.com/arbimon/jobs/clustering
        args:
        - -cpus
        - "4"
        command: ["python",  "./cluster.py"]
        args: ["-e", "${ARG_EPSILON}", "-m", "${ARG_MINSAMPLES}", "-j", "${ARG_CLUSTER_JOBID}", "-a", "${ARG_AED_JOBID}"]
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "${AWS_ACCESS_KEY_ID}"
        - name: AWS_SECRET_ACCESS_KEY
          value: "${AWS_SECRET_ACCESS_KEY}"
        - name: MYSQL_USERNAME
          value: "${MYSQL_USERNAME}"
        - name: MYSQL_PASSWORD
          value: "${MYSQL_PASSWORD}"
        - name: MYSQL_HOSTNAME
          value: "${MYSQL_HOSTNAME}"
        - name: MYSQL_NAME
          value: "${MYSQL_NAME}"
        - name: MYSQL_PORT
          value: "${MYSQL_PORT}"
      imagePullSecrets:
      - name: aedkey
      restartPolicy: Never
  backoffLimit: 0    
